### ISSUE TITLE
Distance and Direction widget - Ellipse - Semi and Full options create same ellipse when using same line dimensions.

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#731] opened 2016-12-16 18:00 UTC
_From @pshowalter on August 11, 2016 19:30_

@MarkTorrey @kgonzago 
Semi and Full options create same ellipse when using same line dimensions.
Choose the Ellipse Type to create.
**Full** means the Axis values are the full width of the ellipse.
**Semi** means the Axis values are only half the width of the ellipse.
If I use same line lengths for Major and Minor, and change Ellipse type from Semi to Full, the same ellipse results.  I would think one would be about half the size of the other?

![image](https://cloud.githubusercontent.com/assets/6842145/17601836/00412a9c-5fd8-11e6-976e-a63e98806f49.png)
![image](https://cloud.githubusercontent.com/assets/6842145/17601852/14910d64-5fd8-11e6-84bf-20f614406ec8.png)

![image](https://cloud.githubusercontent.com/assets/6842145/17601881/3a314c50-5fd8-11e6-8d15-98cbbcae1adb.png)

![image](https://cloud.githubusercontent.com/assets/6842145/17601917/5abaa700-5fd8-11e6-9587-c04ab76a872c.png)

_Copied from original issue: Esri/military-tools-webappbuilder#101_

**Comment by lfunkhouser** [comment] 2016-12-16 18:00
_From @kgonzago on December 13, 2016 19:39_

This is by design. An ellipse will be created the same regardless of **Full** or **Semi**, **Full** denotes **Major Axis** and **Minor Axis** lengths are twice the lengths of a **Semi**.

**Comment by kgonzago** [comment] 2016-12-22 17:15
Closing this issue since it's by design.

**Closed by kgonzago** 2016-12-22 17:15 UTC
Labels: 0 - Backlog, B - Bug, Distance and Direction, G - Defense Team
