### ISSUE TITLE
Creating a 1.2 Release

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-webappbuilder-widgets#259] opened 2015-09-01 19:34 UTC
Related to https://github.com/Esri/solutions-webappbuilder-widgets/issues/221

After discussing this w/ @MikeMillerGIS and @conklinbd, we should use the following workflow for creating/releasing widgets in the solutions-webappbuilder-widgets repository: Use pre-releases for individual widgets, and releases for the entire repository. Because we have not done any of this prior to Web AppBuilder for ArcGIS v1.2, our initial release (1.0.0) will be for WAB 1.2. We should use semantic versioning (http://semver.org/), and not dates to track these releases.

For example:
 - Elevation Profile Table 0.1.0 for Web AppBuilder v1.1 (a release previous to 1.0.0)
 - Elevation Profile Table 1.0.0 for Web AppBuilder v1.2
 - Solutions Web AppBuilder Widgets 1.0.0 for Web AppBuilder v1.2

Here is a table that tracks the latest versions and dispositions of the current widgets in the repository:

|Widget|Latest Version|Disposition|
|:---|:---:|:---|
|BatchAttributeEditor|1.2|Needs Minor Release|
|BombThreat|1.2|Needs Minor Release|
|CI_KR_Chart|1.0|Core (Deprecate)|
|CostAnalysis|1.1|??|
|DirectionswithBarriers|1.0|Needs Work (Branch)|
|ERG|1.0|??|
|ElevationProfileTable|1.2|Needs Minor Release|
|ImageDiscovery|1.0|??|
|MissionEditor|??|Needs Work (Branch)|
|NetworkTrace|1.2|Needs Minor Release|
|ServiceFeasability|1.2|Needs Minor Release|
|Swipe|1.0|Core (Deprecate)|

All work should be done in branches, and these branches should be created from the master branch (i.e. directionswithbarriers-v1.2). Once that work is done, the following steps should happen:
 1. Review (Code, Documentation, ITAR, Certification, etc.)
 2. Pre-release (created from the branch)
 3. Merge (back to master, branch deleted)

**Comment by joebayles** [comment] 2015-09-01 19:39
So... maybe this?

Web AppBuilder Widgets 1.0.0
 - BatchAttributeEditor
 - BombThreat
 - ElevationProfileTable
 - NetworkTrace
 - ServiceFeasability

Web AppBuilder Widgets 1.1.0
 - CostAnalysis
 - DirectionswithBarriers
 - ERG
 - ImageDiscovery
 - MissionEditor

**Comment by joebayles** [comment] 2016-02-04 17:49
@mfunk @kgonzago any thoughts?

**Comment by kgonzago** [comment] 2016-02-09 14:10
@joebayles Applying versions to a widget makes sense. Are we still going with one repo per widget?

**Comment by joebayles** [comment] 2016-02-09 14:13
@kgonzago I don't know, I'm out of the decision-making on that. I like the idea of one repository for all widgets, you can still download exactly what you want. Just asked you guys since you're handling this repo for the Defense team now, if I'm not mistaken.

**Comment by kgonzago** [comment] 2016-02-09 14:26
@joebayles The current process for widget creation is a private repo is created for a new widget. Once development and testing are completed for the widget, it is then moved to our solutions widgets repo as another item to download. But we took a different approach with the .NET coordinate tool add-in which has its own repo. I like the idea of a repo per widget, makes it easier from a management perspective. Maybe another discussion is needed with @conklinbd and @MikeMillerGIS.

**Comment by MikeMillerGIS** [comment] 2016-02-18 14:24
Following the logic in this post - http://nvie.com/posts/a-successful-git-branching-model/

I am going to create a 1.3 branch.  We can remove any code not "ready" for 1.3 and create a tag.  As code is 1.3 ready, we can move into that branch and create further release tags.

Does anyone have any objections? @joebayles @conklinbd @kgonzago @previnWong

**Comment by joebayles** [comment] 2016-02-18 14:32
:+1: 
Great article Mike, and I think it's something we should look at incorporating into all of our "cross-team" repositories. @mfunk @pHill5136 thoughts?

**Comment by MikeMillerGIS** [comment] 2016-02-22 12:47
@joebayles @kgonzago @jmhauck @previnWong 

I created a branch for this release.  It currently contains all widgets in master.  Are they all ready for a 1.3 release?  Should sit awareness and filter editing be in there since they are part of core?

BombThreat
CI_KR_Chart
ERG
ElevationProfileTable
FilterEditor
ImageDiscovery
NetworkTrace
ServiceFeasibility
SituationAwareness

**Comment by kgonzago** [comment] 2016-02-24 16:04
@MikeMillerGIS Agreed, FilterEditor should not be there since it's in WAB core. Also, defense related widgets have not been confirmed/tested with 1.3 yet. Thanks for the reminder.

**Comment by MikeMillerGIS** [comment] 2016-03-01 22:32
1.3 release created.  Closing issue - https://github.com/Esri/solutions-webappbuilder-widgets/releases/tag/2_2016_1.3_Release

**Closed by MikeMillerGIS** 2016-03-01 22:32 UTC
Labels: 0 - Backlog, B - Question, G - Release Team
