### ISSUE TITLE
Network Trace - Question: Save to Layer field editability 

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#415] opened 2016-01-26 17:43 UTC
@MikeMillerGIS 

When configuring the network trace widget for water isolation trace, when the results are saved the end user is able to edit the customers, valves, and hydrant count fields (those set up in the overview configuration file) is this by design?

![image](https://cloud.githubusercontent.com/assets/5611508/12589134/22b4120a-c411-11e5-83d8-bac773992532.png)

**Comment by MikeMillerGIS** [comment] 2016-01-26 17:57
If it an editable field, we were not forcing it to be non editable.  Let's flag this as an enhancement.
On Jan 26, 2016 12:43 PM, Clare Price <notifications@github.com> wrote:

@MikeMillerGIS<https://github.com/MikeMillerGIS>

When configuring the network trace widget for water isolation trace, when the results are saved the end user is able to edit the customers, valves, and hydrant count fields (those set up in the overview configuration file) is this by design?

[image]<https://cloud.githubusercontent.com/assets/5611508/12589134/22b4120a-c411-11e5-83d8-bac773992532.png>

**Comment by MikeMillerGIS** [comment] 2016-01-27 15:46
I am going to close this as I feel we should not override if these fields are editable.  I can envision a scenario where a user might want to manually override these.

**Closed by MikeMillerGIS** 2016-01-27 15:46 UTC
Labels: B - Enhancement, G - Utilities Team
