### ISSUE TITLE
Coordinate Conversion: create output MGRS/USNG/UTM coordinate in polar regions

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#782] opened 2017-01-13 00:09 UTC
### Bug or Enhancement
Outside of 80 degree South and 84 degree North, MGRS is defined in terms of Universal Polar Sterographic (UPS). So for example, if you use the Identify tool in ArcMap at 87.7520N 169.6139E, it will switch to using UPS and return the MGRS and USNG value ZAK4500045522, which is the same value that Geotrans will return.

Currently, the widget creates invalid MGRS, USNG and UTM values.

For MGRS and USNG it should create a value based on UPS. Don't believe a UTM value should be generated.

**Comment by adgiles** [comment] 2017-01-16 15:42
@elinz @nfeuerstein 

I am not aware that the geometry service on ArcGIS Server supports UPS, this maybe an enhancement request to core?

Notice there is no mention of UPS in the onvert coordinate notation documentation:

http://pro.arcgis.com/en/pro-app/tool-reference/data-management/convert-coordinate-notation.htm

**Comment by elinz** [comment] 2017-01-16 18:51
@adgiles @nfeuerstein I can't address the geometry service, but the projection engine that is used in ArcMap will return a MGRS coordinate based on the UPS grid automatically in the polar regions. Tested this using the Identify tool in ArcMap north of 84 degrees north.

NOTE: the help doc that you reference is for the Coordinate Conversion gp tool. Please see the MGRS section in this topic https://pro.arcgis.com/en/pro-app/tool-reference/data-management/supported-notation-formats.htm#ESRI_SECTION1_A0D0A81FA4D94FE1A160B3C3D1306069 that mentions UPS.

**Comment by elinz** [comment] 2017-01-16 18:52
@adgiles And this issue is set to Version - After Next so we don't have to worry about it now.

**Comment by adgiles** [comment] 2017-01-20 14:39
@elinz 

I have addressed this issue, the server will return a UPS coordinate if in the polar regions

i know it is marked as next version but in fixing I noticed incorrect values were being created for MGRS and USNG, so I have merged these changes in.

The label for UTM output will switch between UTM/UPS as required:

![untitled](https://cloud.githubusercontent.com/assets/3740334/22153190/348b87e6-df1e-11e6-8ec2-d3d761c74fe5.png)

**Comment by elinz** [comment] 2017-01-20 15:23
@nfeuerstein Please advise.

At this late date, I'm inclined to have @adgiles revert this change. Accepting this change means that we have a major difference between the widget and the Pro and ArcMap addins, i.e the widget handling the polar regions and the addins don't. 

This change would still require some changes as we never should automatically be changing the output format box from UTM to UPS. If we want UPS then that becomes a separate output format on it's own.

**Comment by nfeuerstein** [comment] 2017-01-20 15:43
@elinz @dfoll @adgiles does this fix require doc updates?

**Comment by Dbarnes1** [comment] 2017-01-20 15:44
@nfeuerstein yes it does.

**Comment by nfeuerstein** [comment] 2017-01-20 15:45
@adgiles please revert the change for now.  We can add this back in after we release this version.  This change will require further validation, testing, and documentation updates that we do not have the bandwidth for at this time.

**Comment by adgiles** [comment] 2017-01-20 15:55
According to Eric's description at the top Arcmap does handle the polar regions and returns the correct UPS and MGRS. If the widget is returned to what it was it will be producing incorrect results

**Comment by elinz** [comment] 2017-01-20 16:06
@adgiles ArcMap handles MGRS/USNG in the Polar regions does (i.e Identify tool, Add XY tool), but the Coordinate Conversion addin for Pro and ArcMap do not handle MGRS/USNG in the Polar regions.

**Comment by adgiles** [comment] 2017-01-20 17:17
@nfeuerstein 

The issue is the widget was handling UPS originally but we were not checking for a UPS response so the widget was actually throwing an error. The changes I have made are to catch this and prevent it from happening. In doing so I visually inform the user that they have a UPS coord not a UTM by swapping the label.

You can see the changes I made here:

https://github.com/Esri/solutions-webappbuilder-widgets/commit/d8ebcec9d10e8457aff680600761fb20d917d879

If I revert back the widget will still perform polar conversion but provide wrong results

**Comment by elinz** [comment] 2017-01-20 17:25
@adgiles @nfeuerstein We had already handled this issue for this release by places notes in the widget doc and release notes that polar regions weren't supported for these coordinate systems and that if the addin/widget had produced a value that it was incorrect.

**Comment by nfeuerstein** [comment] 2017-01-20 17:27
@adgiles while we obviously don't want incorrect results, I agree with @elinz that we had already discussed this and agreed that we would address it through documentation this release.  That is why this issue was marked "Version - After Next"

**Comment by elinz** [comment] 2017-01-20 17:29
@adgiles We shouldn't be creating any output for UTM at the Polar regions. I mention this in my initial issue. The identify tool in ArcMap does not return a UTM value when your in the polar regions and neither does GeoTrans.

**Comment by elinz** [comment] 2017-01-20 17:31
ArcMap identify tool DD in polar region...
![image](https://cloud.githubusercontent.com/assets/4635490/22158855/2b14d670-def3-11e6-95fc-6acfc627f4fe.png)

Switching to UTM...
![image](https://cloud.githubusercontent.com/assets/4635490/22158865/37725596-def3-11e6-857f-05a22e4202c1.png)

**Comment by adgiles** [comment] 2017-01-20 17:34
I'm not at my PC to revert the changes so somebody will have to revert them.

**Comment by adgiles** [comment] 2017-01-20 18:23
Cheers Avi

**Comment by elinz** [comment] 2017-01-20 18:24
Thanks @ACueva

**Comment by adgiles** [comment] 2017-01-24 12:36
addressed in branch:  https://github.com/Esri/solutions-webappbuilder-widgets/tree/ag-CoordinateConversion-Dev

Please verify

**Comment by elinz** [comment] 2017-02-06 21:45
@adgiles MGRS and USNG are working correctly. Currently, the widget switches the output format label to UPS for both UTM and UTM (H) and populates these output controls with the corresponding UPS value. For UTM and UTM (H) we should not convert the output to UPS, as the user is expecting UTM. Since UTM is not valid in the polar regions we should leave the output controls labeled as "UTM" and "UTM (H)" and not populate the controls with any values.

Assigning the issue but to you.

**Comment by adgiles** [comment] 2017-05-10 08:16
When in polar regions the label for UTM & UTM(H) no longer change to UPS
and coordinates are left blank (or blanked out if already populated)

**Comment by ACueva** [comment] 2017-05-10 16:03
I got this one.

**Comment by ACueva** [comment] 2017-05-10 16:45
Verified.  New behavior in the polar regions is shown below.
![2017-05-10_9-37-16](https://cloud.githubusercontent.com/assets/3093940/25910302/bd361830-3564-11e7-8166-3e336f4c96ae.png)

Observation:
1. Coordinate Conversion ArcMap addin needs this same behavior added. (Will check and log an issue accordingly)

@topowright @NatalieCampos @dfoll I'm assuming leaving the UTM notation box empty is a valid workflow.  Please chime in if you feel otherwise.

Also, review of documentation needed.  This may have been logged as a known issue. Adding "Affects Documentation" label.

**Comment by ACueva** [comment] 2017-05-11 21:34
This issue was listed in our documentation as a known issue.  Removing it as it no longer is.

Document located here:
/General/ArcGIS Solutions/ArcGIS for Defense/Coordinate Conversion/Web

**Closed by ACueva** 2017-05-11 21:34 UTC
Labels: 3 - Verify, B - Affects Documentation, B - Enhancement, B - Known Issue, Coordinate Conversion, G - Defense Team, Military Tools
