### ISSUE TITLE
Service Feasability - Checking Route Layer causes an error when run

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#189] opened 2015-06-12 16:55 UTC
When checking on "Route Layer" checkbox, and running the tool, a error message saying "fieldInfos is null" appears.
![image](https://cloud.githubusercontent.com/assets/11183838/8135051/05bec6bc-10e9-11e5-972c-9af2ebd37a27.png)

![image](https://cloud.githubusercontent.com/assets/11183838/8135055/0d098448-10e9-11e5-8fe3-45bf9646ebea.png)

![image](https://cloud.githubusercontent.com/assets/11183838/8135057/12313ad8-10e9-11e5-8f1c-e830141e510c.png)

**Comment by CTLocalGovTeam** [comment] 2015-06-15 13:59
@previnWong @MikeMillerGIS We will fix this issue and will include the fix in next release.

**Comment by CTLocalGovTeam** [comment] 2015-06-16 14:53
@previnWong @MikeMillerGIS We were not able to reproduce this issue. Please provide us the steps/configuration to reproduce.

**Comment by CTLocalGovTeam** [comment] 2015-06-23 15:48
@previnWong @MikeMillerGIS 
we referenced this issue in above pull request by mistake. please ignore.

**Comment by MikeMillerGIS** [comment] 2015-06-26 16:28
Closing as I am not able to repo either.  If the issue occurs again, please log an issue with repo steps

**Closed by MikeMillerGIS** 2015-06-26 16:28 UTC
Labels: G - Utilities Team
