### ISSUE TITLE
Need a Visibility Icon

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-webappbuilder-widgets#789] opened 2017-01-15 18:11 UTC
### Widget
Visibility
### Version of widget
1.0
### Bug or Enhancement
We need a proper icon: 
![image](https://cloud.githubusercontent.com/assets/5488313/21964985/deedabaa-db0a-11e6-8ad9-70edbe4a0d94.png)

**Comment by adgiles** [comment] 2017-01-15 19:24
Duplicate of #777

**Comment by adgiles** [comment] 2017-01-16 12:34
I have amended the Near Me icon for visibility as per images:

![2](https://cloud.githubusercontent.com/assets/3740334/21983221/1556a574-dbe8-11e6-9cdb-76d6c88e4701.png)
![1](https://cloud.githubusercontent.com/assets/3740334/21983225/16d823c8-dbe8-11e6-8f6f-bf9f534ea1ca.png)

**Comment by joebayles** [comment] 2017-01-16 17:21
Verified.

**Closed by joebayles** 2017-01-16 17:21 UTC
Labels: 3 - Verify, B - Bug, B - Duplicate
