### ISSUE TITLE
Next looks disabled if i enter into a workflow again

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#995] opened 2017-11-17 22:34 UTC
I accidentally clicked too fast through the Location Information wizard and clicked to accept Single Field, but need to configure Multiple fields.

after clicking into the workflow again, the Next button appears grayed out, even after changing my choice: 

![image](https://user-images.githubusercontent.com/6181441/32971904-5758c496-cba4-11e7-85f1-506ef2c2e109.png)

**Comment by jmhauck** [comment] 2018-01-12 00:02
Not fully complete until #980 is resolved

**Comment by NikkiGolding** [comment] 2018-01-24 00:29
Verified.

**Comment by NikkiGolding** [comment] 2018-01-29 21:35
Closing - Reopened  because i thought i could still reproduce this.  However, i am unable to.

**Closed** 2018-01-29 21:36 UTC
Labels: B - Bug, Critical Facilities, High Priority
