### ISSUE TITLE
Ellipse not drawing when keying in coordinate and other parameters Major, Minor, Unit, Orientation

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#728] opened 2016-12-16 18:00 UTC
_From @pshowalter on August 26, 2016 20:22_

I have keyed in parameters as in screen caputure, but not getting ellipse.

![image](https://cloud.githubusercontent.com/assets/6842145/18019295/539a35b2-6ba9-11e6-97cb-514f5e96dad0.png)

_Copied from original issue: Esri/military-tools-webappbuilder#107_

**Comment by lfunkhouser** [comment] 2016-12-16 18:00
_From @elinz on December 12, 2016 23:36_

@kgonzago @ACueva The fix for this issue was committed to the https://github.com/Esri/solutions-webappbuilder-widgets repo, however, Jenkins is building from this repo.

**Comment by kgonzago** [comment] 2016-12-22 17:28
Verified jenkins is pulling from right repo.

**Comment by elinz** [comment] 2017-01-09 19:31
@kgonzago I've tested, and was able to create an ellipse, but not sure if the input behavior is working as intended. I was testing within web app builder and
@kgonzago 
- Type in 40N 102W in Center point textbox and enter return. The small black circle draws.
- Enter 220000 in the Major textbox and enter return. The major axis is drawn.
- Enter 10000 in the Minor textbox and enter return. The minor axis is drawn.
- Enter 65 in the Orientation Angle and enter return. The black circle, major and minor axis disappear and the ellipse is not drawn.
- I now have to click in each of the textboxes (Center Point, Major, Minor, Orientation Angle) and enter return for the ellipse to draw.

Is this how it was designed to work?

**Comment by adgiles** [comment] 2017-01-10 10:02
@kgonzago @elinz 

When the input box type was changed from a number spinner back to a text box I forgot to check the method for grabbing the value within the box was the same, which is isn't. Changed this.angleInput.value to this.angleInput.displayedValue. Please can you confirm this fixes the issue

**Comment by kgonzago** [comment] 2017-01-10 17:06
@elinz can you verify?

**Comment by elinz** [comment] 2017-01-10 18:51
@adgiles @kgonzago Tested with build 10 Jan 2017 05:53 of the Distance and Direction widget and the behavior for creating an ellipse is what I would expect. 

Now:
- Type in 40N 102W in Center point textbox and enter return. The small black circle draws.
- Enter 220000 in the Major textbox (don't enter return). The major axis is drawn.
- Enter 100000 in the Minor textbox (don't enter return). The minor axis is drawn.
- Enter 65 in the Orientation Angle and enter return. The ellipse _is_ drawn.

Closing issue.

**Closed by elinz** 2017-01-10 18:51 UTC
Labels: 4 - Done, Distance and Direction, G - Defense Team
