### ISSUE TITLE
GRG Widget Configuration Page does not load

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-webappbuilder-widgets#680] opened 2016-12-01 22:56 UTC
### Repo Steps or Enhancement details

I have attempted to use the GRG widget the hosted version of WebApplication Builder on our Portal. I am able to add the widget to the application; however, I am not able to load the configuration page: 

![image](https://cloud.githubusercontent.com/assets/5488313/20816265/52320dfc-b7d6-11e6-8367-82c43d3c00cb.png)

**Comment by topowright** [comment] 2016-12-01 22:56
@kgonzago

**Comment by kgonzago** [comment] 2017-01-17 15:57
@topowright I am unable to reproduce it with the latest build of MTA. Can you verify if issue still persists when you get a chance?

**Comment by Dbarnes1** [comment] 2017-03-16 17:02
![image](https://cloud.githubusercontent.com/assets/13024357/24008719/a352e6a6-0a2f-11e7-9f0e-acd7805aeea6.png)


verifying and closing.

**Closed by Dbarnes1** 2017-03-16 17:02 UTC
Labels: 2 - In Progress, G - Defense Team
