### ISSUE TITLE
Coordinate Conversion: Add support for GEOREF

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#739] opened 2016-12-20 17:50 UTC
### Widget
Coordinate Conversion
### Bug or Enhancement
According to help doc for the Convert Coordinate Notation gp tool: http://pro.arcgis.com/en/pro-app/tool-reference/data-management/convert-coordinate-notation.htm, the gp tool supports the following formats:
DD, DDM, DMS, GARS, GEOREF, UTM, USNG, and MGRS.

The current addin supports all these same formats except: GEOREF - World Geographic Reference System. We should support all the same formats across the addins, widgets, and gp tools.

**Comment by adgiles** [comment] 2017-01-24 12:37
addressed in branch:  https://github.com/Esri/solutions-webappbuilder-widgets/tree/ag-CoordinateConversion-Dev

Please verify

**Comment by lfunkhouser** [comment] 2017-04-28 13:22
Assigning MT PEs (in addition to @elinz ) to verify and check documentation.
FYI: @ACueva @dfoll @topowright @NatalieCampos

**Comment by dfoll** [comment] 2017-04-28 21:58
@adgiles @kgonzago @lfunkhouser  from what i see, GEOREF has not been added into the widget. However I'm not sure that it should be.... the add-ins do not have GEOREF or GARS, not sure we should add it to the widget just because Pro gp documentation says we support it.

**Comment by dfoll** [comment] 2017-04-28 22:39
FYI i got the widget from our build location.... follow on to that, we just confirmed that jenkins was building from the wrong location, however, i still maintain that GEOREF  (nor GARS) should currently be in the widget

**Comment by topowright** [comment] 2017-05-02 22:10
@kgonzago based on the comment from @dfoll I think this is something that needs to be pulled out of the code. 
FYI @nfeuerstein and @lfunkhouser

**Comment by topowright** [comment] 2017-05-02 22:21
FYI @nfeuerstein and @lfunkhouser so we know what you want to do for this issue

**Comment by kgonzago** [comment] 2017-05-04 13:25
@dfoll @topowright to mimic what's offered in the add-ins, I'll remove the GARS and GEOREF options.

**Comment by topowright** [comment] 2017-09-11 17:08
This is now supported in the WAB version 2.5: 
![image](https://user-images.githubusercontent.com/5488313/30287221-272105cc-96d9-11e7-873b-52f8c2d7995c.png)

**Closed by topowright** 2017-09-11 17:08 UTC
Labels: B - Affects Documentation, B - Enhancement, Coordinate Conversion, G - Defense Team, Military Tools
