### ISSUE TITLE
Distance and Direction Configuration Page - Unexpected Behavior when dynamically choosing colors

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-webappbuilder-widgets#834] opened 2017-02-21 17:31 UTC
When working on the Distance and Direction Feedback Style in the configuration page for the widget, I'm realizing that you have to be careful where you click in the color palette pop-ups when choosing Line Color. In order to use the color picker properly, you have to move your cursor over the slider, and then move around. If you click anywhere else either on the color bar or the color palette box, the entire pop up may go blank and be rendered unusable.

To repro:
-Open configuration page for Distance and Direction Widget
-Click on one of the Line Colors, the pop up will appear: 
![image](https://cloud.githubusercontent.com/assets/13024357/23176334/662ebfea-f817-11e6-9e33-a760ed51b61f.png)
-Click on the color bar. I'd expect for the color preview to dynamically change based on where I click. Instead, the pop-up momentarily goes blank, and then appears on a black/white color gradient:
![image](https://cloud.githubusercontent.com/assets/13024357/23176438/cb350e3a-f817-11e6-81d8-21856a072842.png)
-Similarly, if I click on a point in the color box, then the pop up will switch between two colors where some of the RGB values are at 255 and others are at 0. for example, if I click on a location in the color box, R may be 255 with the other two values at 0, and then when I click anywhere else on the color box, the values will flip and 255 will appear on G and B, with R at 0. This behavior is odd, but it is consistent and should be fixed.

@adgiles @kgonzago I think this is unrelated to the unit test updates, but I haven't seen this particular issue documented yet.

**Comment by adgiles** [comment] 2017-02-23 12:51
@Dbarnes1 

I cannot replicate this issue tried using the following browsers:

•Chrome Version 55.0.2883.87
•Firefox Version 50.1.0
•IE Version 11.0.9600.16384

Can you check again and let me know which browser you are using if problem is still present

**Comment by Dbarnes1** [comment] 2017-02-23 22:07
@adgiles I would expect it to work like this color editor in Pro, where I am able to select any color by clicking on any of the bars or anywhere in the color palette: 

![image](https://cloud.githubusercontent.com/assets/13024357/23281242/61ea4e20-f9d1-11e6-9bf8-e479f0e57789.png)

**Comment by adgiles** [comment] 2017-02-24 15:17
@Dbarnes1 

I am still unsure of the issue, the widget is using the colour picker from core development, I can click on the vertical bar or the big colour square and everything works as expected

**Comment by Dbarnes1** [comment] 2017-02-24 16:11
after showing @kgonzago he will investigate what is going on, it looks like it is an issue with core wab.

**Comment by kgonzago** [comment] 2017-02-24 16:18
@Dbarnes1 @adgiles I confirmed it is an issue with the WAB color chooser dijit. I will submit an issue for the dev team to fix.

**Comment by kgonzago** [comment] 2017-02-24 16:54
Submitted the [issue](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/issues/8740). Closing this since it's a core issue.

**Comment by kgonzago** [comment] 2017-02-27 14:59
@Dbarnes1 @adgiles 

FYI, this issue is a known limitation in Chrome. Apparently it doesn't exist in IE nor FF. According to the WAB dev team, it's a bug in the  dojox/widget/ColorPicker, core Dojo bug.

@Dbarnes1 I suggest we doc this as a known limitation for the D&D widget.

**Comment by adgiles** [comment] 2017-05-10 11:22
@NatalieCampos @topowright @dfoll @ACueva

Can somebody Document this known limitation and close this issue once done, Thanks

**Comment by NatalieCampos** [comment] 2017-05-22 23:20
@kgonzago do you know if the core WAB team has fixed this?

**Comment by kgonzago** [comment] 2017-05-23 01:18
@NatalieCampos WAB team doc'ed it as a known limitation.

**Comment by NatalieCampos** [comment] 2017-05-23 17:52
The following was added to the **Known Issues for Military Tools for ArcGIS** topic

> When using the color picker while configuring the app, the RGB values may be  incorrect. Use the color ramp for drag option or the color palette drag option for best results.  

Closing issue

**Closed by NatalieCampos** 2017-05-23 17:52 UTC
Labels: 0 - Backlog, B - Affects Documentation, B - Bug, Distance and Direction, G - Defense Team, Military Tools

**Comment by topowright** [comment] 2017-07-10 20:45
Being that this issue is being addressed via the web app builder team it is no longer an issue that we need to track.
