### ISSUE TITLE
Distance Direction Ellipse Drawing with Arithmetic Rotation in Manual Mode

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#723] opened 2016-12-16 17:59 UTC
_From @pHill5136 on December 13, 2016 20:49_

In manual mode the angle of rotation is arithmetic and should be converted to geographic

_Copied from original issue: Esri/military-tools-webappbuilder#114_

**Comment by adgiles** [comment] 2017-01-10 10:47
@pHill5136   Patrick I am not sure what this bug refers to, the ellipse is drawn with the major axis at the angle specified in the input box; with 0 being north. Please can you confirm if this is still an issue?

**Comment by pHill5136** [comment] 2017-01-10 16:54
![elipse-wab](https://cloud.githubusercontent.com/assets/4691261/21815355/26573720-d711-11e6-84c0-30eddfd958b6.png)

These are ellipses both drawn with a azimuth of 96.5 degrees. The one on left was drawn interactively, the one on right was drawn using manual input. It appears that the manual input ellipse is not converting from arithmetic to geographic rotation. In arithmetic rotation starts at due east and rotates counter clockwise to render 96.5 degrees almost vertical (90 degrees). The interactive ellipse appears to be drawing properly.

**Comment by kgonzago** [comment] 2017-01-10 18:58
@pHill5136 I can't reproduce using the latest. Can you re-verify using the latest widget?

**Comment by pHill5136** [comment] 2017-01-10 21:41
@kgonzago @adgiles After further investigation found I was deploying older version of the widget. This one appears to have already been fixed. closing

**Closed by pHill5136** 2017-01-10 21:41 UTC
Labels: 0 - Backlog, B - Bug, Distance and Direction, G - Defense Team, High Priority
