### ISSUE TITLE
Network Trace - Export to CSV date field format

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#132] opened 2015-04-22 17:25 UTC
@MikeMillerGIS 

In the export to CSV, the date field is inconsistent in formatting. In the case of the screenshot below, the main features that were formated as "NaN-NaN-NaN" were all populated with the date "1/1/1900" 
![image](https://cloud.githubusercontent.com/assets/5611508/7280761/e57bc206-e8d9-11e4-8ee6-51f97872b5e9.png)

**Comment by CTLocalGovTeam** [comment] 2015-04-24 06:57
@clareprice Please provide the screenshot that you have mentioned in above comment.
@MikeMillerGIS

**Comment by clareprice** [comment] 2015-04-29 02:03
![image](https://cloud.githubusercontent.com/assets/5611508/7383723/38593eaa-edd9-11e4-98c7-5355b68917ba.png)
@CTLocalGovTeam

**Comment by CTLocalGovTeam** [comment] 2015-04-30 06:49
@clareprice  We will investigate and fix this in the next release.
@MikeMillerGIS

**Comment by CTLocalGovTeam** [comment] 2015-05-19 08:44
@MikeMillerGIS, we are seeing that pre-epoch dates (dates before 1970) are displayed as 'null' which is incorrect and needs to be fixed. However, we are not able to reproduce display of 'Nan-Nan-Nan'. 

Can you please share a copy of the 'Connected_Mains' layer or a link to the feature service?

**Comment by MikeMillerGIS** [comment] 2015-05-19 09:46
@clareprice can you share this data?

**Comment by clareprice** [comment] 2015-05-19 14:28
@CTLocalGovTeam The connected mains layer is created as a result of the Upstream Trace geoprocessing service. I produced this error using the sample data and geoprocessing service: http://54.203.249.87:6080/arcgis/rest/services/UpstreamTrace/GPServer

**Comment by CTLocalGovTeam** [comment] 2015-05-20 12:41
@MikeMillerGIS, @clareprice, We were able to reproduce this in Sprint 3 (v0.3) code drop. We had delivered Sprint 4 (v1.0) on the same day this issue was logged. Hence, we were trying to repro this in v1.0, without success.

In v1.0, we have noticed that pre-epoch dates (dates before 1970) are displayed as 'null' which is incorrect and a fix for this will be included in next release.

**Comment by MikeMillerGIS** [comment] 2015-06-09 20:22
verified

**Closed by MikeMillerGIS** 2015-06-09 20:22 UTC
Labels: B - Bug, G - Utilities Team
